### ISSUE TITLE
Clicking outside of MT window unbinds cursor

### ISSUE THREAD

**Issue by seagull** [archindivide/MouseTrapper#1]
[ScreenCapture_20-01-2017 09.24.13A.zip](https://github.com/archindivide/MouseTrapper/files/718932/ScreenCapture_20-01-2017.09.24.13A.zip)

Mouse binding works great until the user clicks on something – then it's lost.
You can repro this by opening paint and attempting to draw a box.

**Comment by archindivide** [comment]
This issue has been corrected, with commit bd6e053c67e330c774405599ea617adf95bf711d
